
FROM ubuntu:20.04

#Para que tenga permisos para ejecutar Docker
USER root

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

#Ubuntu se queda pillado al instalar algunos paquetes porque necesita establecer la zona horaria
RUN apt-get update && apt-get install -y tzdata
RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

# Actualiza e instala las dependencias del sistema
RUN apt-get update && apt-get install -y \
    pip \
    python3-dev \
    build-essential \
    libatlas-base-dev \
    libblas-dev \
    liblapack-dev \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

# Instalación de dependencias para poder usar Docker
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    lsb-release \
    && curl -fsSL https://get.docker.com | sh

# Actualiza pip a la última versión
RUN pip install --no-cache-dir --upgrade pip

# Copia solo el archivo requirements.txt primero para aprovechar la caché de Docker
COPY requirements.txt /app/

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación
COPY . /app/

# Define el comando por defecto para ejecutar la aplicación
CMD ["python3", "app.py"]


